### ISSUE TITLE
Can't create config

### ISSUE THREAD

**Issue by Vlix** [NoRedInk/tracing-newrelic#3]
I've done pretty much everything necessary to make this work. I've built the `tracing-newrelic` library, that worked, it compiled, no problem. I've downloaded the New Relic C SDK, built it using `make` and started it up with `./newrelic-daemon --logfile stdout --loglevel debug`, got nice startup printing to stdout and then ran my test program in Haskell, which immediately does `createAppConfig`, but it throws a `CantCreateAppConfig` exception and that's it.

What am I doing wrong? The daemon is on `/tmp/.newrelic.socket` and listening, and everything compiles and type checks. The `AppName` is not empty and the `LicenseKey` is correct (40 characters).
According to the `tracing-newrelic` source code, the `AppConfig` pointer is `NULL`, but the C SDK source code shows it's only NULL when the app name is NULL or the license key is NULL or a wrong length?

**Comment by jwoudenberg** [comment]
Hi @Vlix! Everything you write sounds right to me. The error you're describing is not something we've ran into before.

Is it possible for you to share the source for the test program you're trying this out with? I'd be happy to try it out on my machine, see if I can reproduce the problem.

**Comment by Vlix** [comment]
Thank you for the reply! I'm a bit busy this week, but I'll try to setup a minimum reproduceable test near the end of the week or in the weekend.

**Comment by Vlix** [comment]
Ok, uhmmm, seems like it works now? 😕 (Hadn't actually changed anything)
I thought it might have been the tweaks I made to have everything build with the `v1.3.0` of the `c-sdk`, or that I was running it in a Docker... but no, it works. Got a transaction with segments into NewRelic... and seems A-OK.

Apologies for creating a non-issue. And thanks for the response at least.

We'll be using this in our production code as well, so it's good to know there's help if needed.

**Comment by jwoudenberg** [comment]
No worries, happy to hear it's working for you! Let us know if you run into any more issues!
